---
defaults:
  admins: &1
    class_name: all
    email: mytea@world.com
    phone: '15859859888'
    password: myteaworld
  users: &2
    class_name: User
    opening: 0
    pending: 1
    rejected: 2
    passed: 3
    opening_title: 新用户
    pending_title: 待审核
    rejected_title: 不通过
    passed_title: 通过
    phone: 电话
    password: 密码
    password_confirmation: 确认密码
    name: 姓名
    identity: 身份证
    alipay: 支付宝
    status: 认证状态
  roles: &3
    class_name: Role
    super_admin: 超级管理员
    buyer: 客户信息管理
    tax_category: 商品税收分类编码库管理
    invoice: 发票管理
  permissions: &4
    super_admin: 管理系统所有资源
  citrines: &5
    exchange_max: 300
    count: 可用茶晶
    total: 茶晶总数
  awards: &6
    ten_citrine: 10
    one_citrine: 1
  wares: &7
    title: 宝贝标题
    price: 价格
    citrine_count: 赠送茶晶数
    freight: 运费
    description: 宝贝详情
    category: 分类
    brand: 品牌
    up: 1
    up_title: 上架
    down: 0
    down_title: 下架
  trees: &8
    name: 名字
    count: 茶树数量
  leafs: &9
    produce_max: 12
    pick: 已采摘
    unpick: 未采摘
    count: 茶叶数量
    pick_time: 采摘时间
    disable: 0
    enable: 1
  notices: &10
    title: 标题
    content: 内容
  orders: &11
    category_none: none
    category_recharge: recharge
    paid: paid
    state_none: 0
    state_trade_created: 1
    state_trade_success: 2
    state_trade_failed: 3
    state_none_string: 未定义
    state_trade_created_string: 已创建
    state_trade_success_string: 支付成功
    state_trade_failed_string: 支付失败
  accounts: &12
    coin: 金额
    password: 安全密码
    number: 卡号
    award_sign_up: 10
    award_check_in: 5
    award_share: 30
    award_invite_sign_up: 10
    award_invite_recharge: 40
    enable: enable
    disable: disable
  consumes: &13
    number: 消费编号
    category: 项目
    coin_cost: 消费
    coin_now: 余额
    status: 状态
    category_none: none
    category_recharge: 充值
    category_purchase_leaf: 求购茶叶
    category_exchange_tree: 兑换茶树
    category_buy_ware: 购买茶叶商品
    category_buy_ware_citrine: 购买商品奖励茶晶
    category_buy_commision: 佣金奖励 
    status_none: none
    status_create: create
    status_success: success
    status_failed: failed
    status_exception: exception
  demands: &14
    price: 单价
    count: 数量
    enable: enable
    disable: disable
  sells: &15
    price: 单价
    count: 数量
    enable: enable
    disable: disable
  systems: &16
    poundage: 0.1
    commision: 0.1
    host: 120.55.50.204
  trade_orders: &17
    number: 订单编号
    price: 价格
    state: 状态
    name: 姓名
    phone: 电话
    address: 地址
    wayno: 物流信息
    opening: opening
    opening_title: 新建
    pending: pending
    pending_title: 待支付
    paid: paid
    paid_title: 已支付,待发货
    departed: departed
    departed_title: 已发货
    completed: completed
    completed_title: 已完成
    canceled: canceled
    canceled_title: 已取消
  extract_cashes: &18
    coin: 提取金额
    status: 状态
    pending: pending
    pending_title: 待审核
    agree: agree
    agree_title: 同意 
    disagree: disagree
    disagree_title: 不同意 
  share_pools: &19
    today_enter: 今日入账
    total: 月分红池总额度
    user_total: 昨日分红池总额
    pay: 昨日白银茶主平均分红
    ware_total: 昨日黄金茶主平均分红
    gross_sale: 昨日铂金茶主平均分红
    diamond: 昨日钻石茶主平均分红
    current_total: 分红池当月总额
    own_tea: 持茶/片所得
development:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
  citrines: *5
  awards: *6
  wares: *7
  trees: *8
  leafs: *9
  notices: *10
  orders: *11
  accounts: *12
  consumes: *13
  demands: *14
  sells: *15
  systems: *16
  trade_orders: *17
  extract_cashes: *18
  share_pools: *19
  pick_records:
    number: 数量
  trades:
    min: 交易最低价
    max: 交易最高价
    total_purchase: 今日总求购
    price: 今日茶叶价
    volume: 今日成交量
    start: 交易开始时间
    end: 交易结束时间
    start_default: '09:00'
    end_default: '16:00'
test:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
  citrines: *5
  awards: *6
  wares: *7
  trees: *8
  leafs: *9
  notices: *10
  orders: *11
  accounts: *12
  consumes: *13
  demands: *14
  sells: *15
  systems: *16
  trade_orders: *17
  extract_cashes: *18
  share_pools: *19
production:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
  citrines: *5
  awards: *6
  wares: *7
  trees: *8
  leafs: *9
  notices: *10
  orders: *11
  accounts: *12
  consumes: *13
  demands: *14
  sells: *15
  systems: *16
  trade_orders: *17
  extract_cashes: *18
  share_pools: *19
