---
defaults:
  admins: &1
    class_name: all
    email: admin@qq.com
    phone: '15854752120'
  users: &2
    class_name: User
    opening: 0
    pending: 1
    rejected: 2
    passed: 3
    opening_title: 新用户
    pending_title: 待审核
    rejected_title: 不通过
    passed_title: 通过
    phone: 电话
    password: 密码
    password_confirmation: 确认密码
    name: 姓名
    identity: 身份证
    alipay: 支付宝
    status: 认证状态
  roles: &3
    class_name: Role
    super_admin: 超级管理员
    buyer: 客户信息管理
    tax_category: 商品税收分类编码库管理
    invoice: 发票管理
  permissions: &4
    super_admin: 管理系统所有资源
development:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
  citrines:
    exchange_max: 500
  awards:
    ten_citrine: 10
    one_citrine: 1
  wares:
    title: 宝贝标题
    price: 价格
    citrine_count: 赠送茶晶数
    freight: 运费
    description: 宝贝详情
    category: 分类
    brand: 品牌
    up: 1
    up_title: 上架
    down: 0
    down_title: 下架
  trees:
    name: 名字
    count: 茶树数量
  leafs:
    produce_max: 12
    pick: 已采摘
    unpick: 未采摘
    count: 茶叶数量
    pick_time: 采摘时间
    disable: 0
    enable: 1
  notices:
    title: 标题
    content: 内容
  orders:
    category_none: none
    category_recharge: recharge
    paid: paid
    state_none: 0
    state_trade_created: 1
    state_trade_success: 2
    state_trade_failed: 3
    state_none_string: 未定义
    state_trade_created_string: 已创建
    state_trade_success_string: 支付成功
    state_trade_failed_string: 支付失败
  accounts:
    coin: 金额
    password: 安全密码
    award_sign_up: 10
    award_check_in: 5
    award_share: 30
    award_invite_sign_up: 10
    award_invite_recharge: 40
    enable: enable
    disable: disable
  consumes:
    number: 消费编号
    category: 项目
    coin_cost: 消费
    coin_now: 余额
    status: 状态
    category_none: none
    category_purchase_leaf: 求购茶叶
    category_exchange_tree: 兑换茶树
    category_download_document: download_document
    category_buy_document: buy_document
    status_none: none
    status_create: create
    status_success: success
    status_failed: failed
    status_exception: exception
  demands:
    price: 单价
    count: 数量
    enable: enable
    disable: disable
  sells:
    price: 单价
    count: 数量
    enable: enable
    disable: disable
  systems:
    poundage: 0.1
  trade_orders:
    number: 订单编号
    price: 价格
    state: 状态
    name: 姓名
    phone: 电话
    address: 地址
    wayno: 物流信息
    opening: opening
    opening_title: 新建
    pending: pending
    pending_title: 待支付
    paid: paid
    paid_title: 已支付,待发货
    departed: departed
    departed_title: 已发货
    completed: completed
    completed_title: 已完成
    canceled: canceled
    canceled_title: 已取消
  extract_cashes:
    coin: 提取金额
    status: 状态
    pending: pending
    pending_title: 待审核
    agree: agree
    agree_title: 已提现
test:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
production:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
