---
defaults:
  admins: &1
    class_name: all
    email: admin@qq.com
  users: &2
    class_name: User
    opening: 0
    pending: 1
    rejected: 2 
    passed: 3
    opening_title: 新用户
    pending_title: 待审核
    rejected_title: 不通过
    passed_title: 通过
  roles: &3
    class_name: Role
    super_admin: 超级管理员
    buyer: 客户信息管理
    tax_category: 商品税收分类编码库管理
    invoice: 发票管理
  permissions: &4
    super_admin: 管理系统所有资源
development:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
  wares:
    title: 宝贝标题
    price: 价格
    citrine_count: 赠送茶晶数
    freight: 运费
    description: 宝贝详情
    category: 分类
    brand: 品牌
    up: 1
    up_title: 上架
    down: 0
    down_title: 下架
  trees:
    name: 名字
    count: 茶树数量
  leafs:
    pick: 已采摘
    unpick: 未采摘
    count: 茶叶数量
    pick_time: 采摘时间
test:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
production:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
