---
defaults:
  admins: &1
    class_name: all
    email: admin@qq.com
  users: &2
    class_name: User
  roles: &3
    class_name: Role
    super_admin: 超级管理员
    buyer: 客户信息管理
    tax_category: 商品税收分类编码库管理
    invoice: 发票管理
  permissions: &4
    super_admin: 管理系统所有资源
development:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
test:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
production:
  admins: *1
  users: *2
  roles: *3
  permissions: *4
